# RStudio and RMarkdown

This chapter will serve as a (currently brief) collection of tutorials for using RStudio and RMarkdown. It will likely be expanded over time. At this time many resources also appear in the previous chapter. Over time some may be moved here.

The following videos were made as an introduction to `R`, RStudio, and RMarkdown for STAT 420 at UIUC.

- [RStudio Basics](https://mediaspace.illinois.edu/media/%5BSTAT+420%5D+R+and+RStudio/1_ihjnvfis)
- [RMarkdown Intro](https://mediaspace.illinois.edu/media/%5BSTAT+420%5D+RMarkdown+Intro/1_36pkjkie)
- [RMarkdown Basics](https://mediaspace.illinois.edu/media/%5BSTAT+420%5D+RMarkdown+Basics/1_u0mk6uaq)
- [RMarkdown Tips and Tricks](https://mediaspace.illinois.edu/media/%5BSTAT+420%5D+RMarkdown+Tips+and+Tricks/1_ahkzbeka)

Note that RStudio and RMarkdown and constantly receiving excellent support and updates, so these videos already contain some outdated information. For example, as of recent RStudio versions, the "Import Dataset" functionality has been updated to utilize the [`readr`](https://github.com/tidyverse/readr) and [`tibble`](https://cran.r-project.org/web/packages/tibble/vignettes/tibble.html) packages. Additionally, working interactively with RMarkdown documents in RStudio has a long list of new functionality.

[RStudio](http://rmarkdown.rstudio.com/) provides their own [tutorial for RMarkdown](http://rmarkdown.rstudio.com/lesson-1.html). They also have an excellent [RStudio "cheatsheets"](https://www.rstudio.com/wp-content/uploads/2016/01/rstudio-IDE-cheatsheet.pdf) which visually identifies many of the features available in the IDE.


## Template

[This `.zip` file](https://daviddalpiaz.github.io/stat430sp17/rmd_template/rmd-template.zip) contains the files necessary to produce [this rendered document](https://daviddalpiaz.github.io/stat430sp17/rmd_template/rmd-template.html). This document is a more complete version of a template than what is seen in the above videos.
