# Non-Linear Models

```{r load_library}
library(ISLR)
```

# Polynomial Regression

```{r}
fitPoly4 <- lm(wage ~ poly(age, 4), data = Wage)
summary(fitPoly4)

fitPoly4Raw <- lm(wage ~ poly(age, 4, raw = TRUE), data = Wage)
summary(fitPoly4Raw)

plot(fitted(fitPoly4), fitted(fitPoly4Raw))
```


```{r plot_poly_fit}
ageLower <- range(Wage$age)[1]
ageUpper <- range(Wage$age)[2]
ageGrid <- seq(from = ageLower, to = ageUpper, by = 1)

agePred <- predict(fitPoly4, newdata = data.frame(age = ageGrid), se = TRUE)
ageSeBands <- cbind(agePred$fit+2*agePred$se.fit,agePred$fit-2*agePred$se.fit)

plot(Wage$age, Wage$wage,
  cex = .5, col = "darkgrey",
  xlab = "Age", ylab = "Wage"
)
lines(ageGrid, agePred$fit, lwd = 2, col = "blue")
matlines(ageGrid, ageSeBands, lwd = 1, col = "blue", lty = 3)
```

## ANOVA

```{r anova}
fitA <- lm(wage ~ education, data = Wage)
fitB <- lm(wage ~ education + age, data = Wage)
fitC <- lm(wage ~ education + poly(age, 2), data = Wage)
fitD <- lm(wage ~ education + poly(age, 3), data = Wage)
anova(fitA, fitB, fitC, fitD)
```

# Logistic Regression, Polynomial Terms

```{r logistic}
glmPoly4 <- glm(I(wage > 250) ~ poly(age, 3), data = Wage, family = binomial)
summary(glmPoly4)


glmPred <- predict(glmPoly4, newdata = data.frame(age = ageGrid), se = TRUE)
glmSeBands <- cbind(fit = glmPred$fit,
                    lower = glmPred$fit - 2 * glmPred$se.fit,
                    upper = glmPred$fit + 2 * glmPred$se.fit)

glmProbBands = exp(glmSeBands) / (1 + exp(glmSeBands))
matplot(ageGrid, glmProbBands,
        lwd = c(2, 1, 1), lty = c(1, 2, 2),
        type = "l", col = "red",
        ylim = c(0, 0.1))
points(jitter(Wage$age), I((Wage$wage > 250) / 10),
       cex = .5, pch = "|", col = "darkgrey"
)
```

# Step Functions

```{r step_functions}
table(cut(Wage$age, 4))
stepFit <- lm(wage ~ cut(age, 4), data = Wage)
agePred <- predict(stepFit, newdata = data.frame(age = ageGrid), se = TRUE)
coef(summary(stepFit))

plot(Wage$age, Wage$wage,
     cex = .5, col = "darkgrey",
     xlab = "Age", ylab = "Wage"
)
lines(ageGrid, agePred$fit, col = "red", lwd = 3)
```









# Splines

```{r splines}
library(splines)
cubicFit <- lm(wage ~ bs(age, knots = c(25, 40, 60)), data = Wage)
cubicPred <- predict(cubicFit, newdata = list(age = ageGrid), se = TRUE)
plot(Wage$age, Wage$wage,
     cex = .5, col = "darkgrey",
     xlab = "Age", ylab = "Wage"
)
lines(ageGrid, cubicPred$fit, lwd = 3, col = "darkgreen")
lines(ageGrid, cubicPred$fit + 2 * cubicPred$se, lty = "dashed", col = "darkgreen")
lines(ageGrid, cubicPred$fit - 2 * cubicPred$se, lty = "dashed", col = "darkgreen")
abline(v = c(25, 40, 60), lty = 2)

# Natural Cubic Splines
nCubicFit <- lm(wage ~ ns(age, df = 4), data = Wage)
nCubicPred <- predict(nCubicFit, newdata = list(age = ageGrid), se = TRUE)
plot(Wage$age, Wage$wage,
     cex = .5, col = "darkgrey",
     xlab = "Age", ylab = "Wage"
)
lines(ageGrid, nCubicPred$fit, lwd = 3, col = "darkgreen")
lines(ageGrid, nCubicPred$fit + 2 * nCubicPred$se, lty = "dashed", col = "darkgreen")
lines(ageGrid, nCubicPred$fit - 2 * nCubicPred$se, lty = "dashed", col = "darkgreen")
abline(v = c(25, 40, 60), lty = 2)
```



## Smoothing Splines

```{r smooth_spline}
ssAge <- smooth.spline(Wage$age, Wage$wage, df = 16)
plot(Wage$age, Wage$wage,
     cex = .5, col = "darkgrey",
     xlab = "Age", ylab = "Wage"
)
lines(ssAge, col = "red", lwd = 2)

ssAgeCV <- smooth.spline(Wage$age, Wage$wage, cv = TRUE)
ssAgeCV
lines(ssAgeCV, col = "blue", lwd = 2)
```


# Local Regression


```{r local}
plot(Wage$age, Wage$wage,
     cex = .5, col = "darkgrey",
     xlab = "Age", ylab = "Wage"
)
title("Local Regression")
localSpan02 <- loess(wage ~ age, span = .2, data = Wage)
localSpan05 <- loess(wage ~ age, span = .5, data = Wage)
lines(ageGrid, predict(localSpan02, data.frame(age = ageGrid)),
      col = "red", lwd = 2)
lines(ageGrid, predict(localSpan05, data.frame(age = ageGrid)),
      col = "blue", lwd = 2)
legend("topright", legend = c("Span = 0.2", "Span = 0.5"),
       col = c("red", "blue"), lty = 1, lwd = 2, cex = .8)
```






# Generalized Additive Models (GAMs)


```{r gams}
library(gam)

gamFit <- gam(wage ~ s(age, 4) + s(year, 4) + education, data = Wage)
par(mfrow = c(1, 3))
plot(gamFit, se = TRUE, col = "red", lwd = 2)

gamFitSmall <- gam(wage ~ s(age, 4) + education, data = Wage)
anova(gamFitSmall, gamFit, test = "F")

gamLog <- gam(I(wage > 250) ~ s(age, 4) + s(year, 4) + education,
              family = binomial, data = Wage)
plot(gamLog)
plot(gamLog, se = TRUE, col = "green")
```



## GAMs in `caret`

- TODO
